---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tk-system
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.1.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: grafana-config
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 10
            successThreshold: 1
          resources:
            limits:
              cpu: 30m
              memory: 100Mi
            requests:
              cpu: 30m
              memory: 100Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: config-volume
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: config-volume
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: dashboards-prometheus-volume
              mountPath: /tmp/dashboards-prometheus
            - name: dashboards-node-volume
              mountPath: /tmp/dashboards-node
            - name: dashboards-k8s-volume
              mountPath: /tmp/dashboards-k8s
            - name: dashboards-loki-volume
              mountPath: /tmp/dashboards-loki
            - name: storage-volume
              mountPath: /var/lib/grafana
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
      volumes:
        - name: config-volume
          configMap:
            name: grafana-config
        - name: dashboards-prometheus-volume
          configMap:
            name: grafana-dashboards-prometheus
        - name: dashboards-node-volume
          configMap:
            name: grafana-dashboards-node
        - name: dashboards-k8s-volume
          configMap:
            name: grafana-dashboards-k8s
        - name: dashboards-loki-volume
          configMap:
            name: grafana-dashboards-loki
        - name: storage-volume
          emptyDir: {}
