---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tk-system
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:2.5
          imagePullPolicy: IfNotPresent
          args:
            - --api.insecure
            - --api.dashboard
            - --log.level=INFO
            - --log.filePath=/var/log/traefik/traefik.log
            - --accesslog
            - --accesslog.filePath=/var/log/traefik/access.log
            - --ping
            - --providers.kubernetescrd
            - --providers.kubernetesingress
            - --entryPoints.traefik.address=:8080
            - --entrypoints.web.address=:8000
            - --entrypoints.web.forwardedheaders.insecure
            # - --entrypoints.websecure.address=:8443
            # - --entrypoints.tcpep.address=:8888
            # - --entrypoints.udpep.address=:8888/udp
            # - --certificatesresolvers.default.acme.tlschallenge
            # - --certificatesresolvers.default.acme.email=foo@you.com
            # - --certificatesresolvers.default.acme.storage=acme.json
            # # Please note that this is the staging Let's Encrypt server.
            # # Once you get things working, you should remove that whole line altogether.
            # - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: admin
              containerPort: 8080
            - name: web
              containerPort: 8000
            # - name: websecure
            #   containerPort: 8443
            # - name: tcpep
            #   containerPort: 8888
            # - name: udpep
            #   containerPort: 8888
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 150m
              memory: 200Mi
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
            - name: container-log
              mountPath: /var/log/traefik
        - name: fluent-bit
          image: fluent/fluent-bit:1.8
          # image: grafana/fluent-bit-plugin-loki:1.5.0-amd64
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: fluent-bit-config
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 2020
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 30m
              memory: 30Mi
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/append_tag.lua
              subPath: append_tag.lua
            - name: container-log
              mountPath: /var/log/container
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: container-log
          emptyDir: {}
      securityContext:
        fsGroup: 65532
