---
apiVersion: v1
kind: Service
metadata:
  namespace: tk-system
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: admin
      port: 8080
    # - protocol: TCP
    #   name: websecure
    #   port: 8443
    # - protocol: TCP
    #   name: tcpep
    #   port: 8888
    # - protocol: UDP
    #   name: udpep
    #   port: 8888
