---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tk-system
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      max_transfer_retries: 0
      chunk_retain_period: 1m
      chunk_idle_period: 5m
      chunk_block_size: 262144
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        shared_store: s3
      aws:
        s3: s3://${S3_BUCKET_REGION}/${S3_BUCKET_NAME}
    chunk_store_config:
      max_look_back_period: 168h
    schema_config:
      configs:
        - from: 2018-04-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 336h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: s3
      compaction_interval: 5m
