---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: tk-system
    name: fluentd
  spec:
    selector:
      app: fluentd
    ports:
      - protocol: TCP
        name: forward
        port: 24224
