---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tk-system
  name: prometheus-alertmanager-config
data:
  alertmanager.yml: |
    global: {}
    receivers:
      - name: default-receiver
        webhook_configs:
          - url: http://traefik:8000/?dog=dog
    route:
      receiver: default-receiver
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
