---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
  namespace: tk-system
spec:
  selector:
    app: prometheus-alertmanager
  ports:
    - name: http
      protocol: TCP
      port: 9093
    - name: meshpeer
      protocol: TCP
      port: 9094
