---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tk-system
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      initContainers:
        - name: restore
          image: public.ecr.aws/bitnami/aws-cli:2
          command:
            - sh
            - -c
            - |
              if aws s3 ls "s3://${S3_BUCKET_NAME}/${S3_OBJECT_KEY_PREFIX}snapshots.tar.gz" > /dev/null; then
                aws s3 cp "s3://${S3_BUCKET_NAME}/${S3_OBJECT_KEY_PREFIX}snapshots.tar.gz" /tmp
                cd /data
                tar zxf /tmp/snapshots.tar.gz
              fi
          envFrom:
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: prometheus-config
          volumeMounts:
            - name: storage-volume
              mountPath: /data
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.29.2
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/config/prometheus.yml
            - --web.enable-admin-api
            - --web.enable-lifecycle
            - --web.console.templates=/etc/prometheus/consoles
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --storage.tsdb.path=/data
            - --storage.tsdb.retention.time=15d
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: rules-volume
              mountPath: /etc/rules
            - name: storage-volume
              mountPath: /data
        - name: backup
          image: public.ecr.aws/bitnami/aws-cli:2
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              URL=http://localhost:9090/api/v1/admin/tsdb/snapshot
              cd /tmp
              curl -o jq -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
              chmod +x jq
              while true; do
                sleep 3600
                NAME=$(curl -XPOST "${URL}" | ./jq -r '.data.name')
                (
                  cd "/data/snapshots/${NAME}"
                  tar zcf /tmp/snapshots.tar.gz ./*
                )
                NOW=$(date +%Y-%m%d-%H%M%S)
                aws s3 cp /tmp/snapshots.tar.gz "s3://${S3_BUCKET_NAME}/${S3_OBJECT_KEY_PREFIX}${NOW}.tar.gz"
                aws s3 cp /tmp/snapshots.tar.gz "s3://${S3_BUCKET_NAME}/${S3_OBJECT_KEY_PREFIX}"
                rm -rf "/data/snapshots/${NAME}"
              done
          envFrom:
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: prometheus-config
          resources:
            limits:
              cpu: 40m
              memory: 100Mi
            requests:
              cpu: 40m
              memory: 100Mi
          volumeMounts:
            - name: storage-volume
              mountPath: /data
        - name: configmap-reload
          image: jimmidyson/configmap-reload:v0.5.0
          imagePullPolicy: IfNotPresent
          args:
            - --volume-dir=/etc/config
            - --volume-dir=/etc/rules
            - --webhook-url=http://127.0.0.1:9090/-/reload
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            - name: rules-volume
              mountPath: /etc/rules
              readOnly: true
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: rules-volume
          configMap:
            name: prometheus-rules
        - name: storage-volume
          emptyDir: {}
